In [1]:
# https://www.datacamp.com/community/tutorials/ensemble-learning-python
#
# Models with high variance ( overfit the data ) -> bagging
# Biased models -> boosting ( /!\ poor probability estimate )
#
# 3 Different types of Ensemble learning methods :
#
# Bagging based Ensemble learning
# Boosting-based Ensemble learning
# Voting based Ensemble learning

In [ ]:
# Modules

import pandas as pd
import numpy as np
from sklearn.preprocessing import Imputer
from sklearn.preprocessing import MinMaxScaler

In [40]:
## dataframe 

# Import du csv
df = pd.read_csv('D:\\Fabrice\\datascience\\breast_cancer_wisconsin.csv')

# Suppression de la colonne Unnamed: 32

df.drop(['Unnamed: 32'] , axis = 1 , inplace = True )

# colonne id comme indexe du df

df.set_index( 'id' , drop = True , append = False , inplace = True , verify_integrity = False)
             
# colonnes de df

df.columns

Index(['diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst'],
      dtype='object')

In [41]:
# 1ers enregistrements de df

df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
id                                                                         
842302           M        17.99         10.38          122.80     1001.0   
842517           M        20.57         17.77          132.90     1326.0   
84300903         M        19.69         21.25          130.00     1203.0   
84348301         M        11.42         20.38           77.58      386.1   
84358402         M        20.29         14.34          135.10     1297.0   

          smoothness_mean  compactness_mean  concavity_mean  \
id                                                            
842302            0.11840           0.27760          0.3001   
842517            0.08474           0.07864          0.0869   
84300903          0.10960           0.15990          0.1974   
84348301          0.14250           0.28390          0.2414   
84358402          0.10030           0.13280          0.1980   

          concave points_mean  symmetry_mean           ...             \
id                                                     ...              
842302                0.14710         0.2419           ...              
842517                0.07017         0.1812           ...              
84300903              0.12790         0.2069           ...              
84348301              0.10520         0.2597           ...              
84358402              0.10430         0.1809           ...              

          radius_worst  texture_worst  perimeter_worst  area_worst  \
id                                                                   
842302           25.38          17.33           184.60      2019.0   
842517           24.99          23.41           158.80      1956.0   
84300903         23.57          25.53           152.50      1709.0   
84348301         14.91          26.50            98.87       567.7   
84358402         22.54          16.67           152.20      1575.0   

          smoothness_worst  compactness_worst  concavity_worst  \
id                                                               
842302              0.1622             0.6656           0.7119   
842517              0.1238             0.1866           0.2416   
84300903            0.1444             0.4245           0.4504   
84348301            0.2098             0.8663           0.6869   
84358402            0.1374             0.2050           0.4000   

          concave points_worst  symmetry_worst  fractal_dimension_worst  
id                                                                       
842302                  0.2654          0.4601                  0.11890  
842517                  0.1860          0.2750                  0.08902  
84300903                0.2430          0.3613                  0.08758  
84348301                0.2575          0.6638                  0.17300  
84358402                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [42]:
# Nombre de lignes et de colonnes de df 

df.shape

(569, 31)

In [43]:
# statistiques élémentaires pour les variables quantitatives de df

df.describe()

radius_mean  texture_mean  perimeter_mean    area_mean  \
count   569.000000    569.000000      569.000000   569.000000   
mean     14.127292     19.289649       91.969033   654.889104   
std       3.524049      4.301036       24.298981   351.914129   
min       6.981000      9.710000       43.790000   143.500000   
25%      11.700000     16.170000       75.170000   420.300000   
50%      13.370000     18.840000       86.240000   551.100000   
75%      15.780000     21.800000      104.100000   782.700000   
max      28.110000     39.280000      188.500000  2501.000000   

       smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813        0.079720             0.038803   
min           0.052630          0.019380        0.000000             0.000000   
25%           0.086370          0.064920        0.029560             0.020310   
50%           0.095870          0.092630        0.061540             0.033500   
75%           0.105300          0.130400        0.130700             0.074000   
max           0.163400          0.345400        0.426800             0.201200   

       symmetry_mean  fractal_dimension_mean           ...             \
count     569.000000              569.000000           ...              
mean        0.181162                0.062798           ...              
std         0.027414                0.007060           ...              
min         0.106000                0.049960           ...              
25%         0.161900                0.057700           ...              
50%         0.179200                0.061540           ...              
75%         0.195700                0.066120           ...              
max         0.304000                0.097440           ...              

       radius_worst  texture_worst  perimeter_worst   area_worst  \
count    569.000000     569.000000       569.000000   569.000000   
mean      16.269190      25.677223       107.261213   880.583128   
std        4.833242       6.146258        33.602542   569.356993   
min        7.930000      12.020000        50.410000   185.200000   
25%       13.010000      21.080000        84.110000   515.300000   
50%       14.970000      25.410000        97.660000   686.500000   
75%       18.790000      29.720000       125.400000  1084.000000   
max       36.040000      49.540000       251.200000  4254.000000   

       smoothness_worst  compactness_worst  concavity_worst  \
count        569.000000         569.000000       569.000000   
mean           0.132369           0.254265         0.272188   
std            0.022832           0.157336         0.208624   
min            0.071170           0.027290         0.000000   
25%            0.116600           0.147200         0.114500   
50%            0.131300           0.211900         0.226700   
75%            0.146000           0.339100         0.382900   
max            0.222600           1.058000         1.252000   

       concave points_worst  symmetry_worst  fractal_dimension_worst  
count            569.000000      569.000000               569.000000  
mean               0.114606        0.290076                 0.083946  
std                0.065732        0.061867                 0.018061  
min                0.000000        0.156500                 0.055040  
25%                0.064930        0.250400                 0.071460  
50%                0.099930        0.282200                 0.080040  
75%                0.161400        0.317900                 0.092080  
max                0.291000        0.663800                 0.207500  

[8 rows x 30 columns]

In [44]:
# informations générales sur df

df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 569 entries, 842302 to 92751
Data columns (total 31 columns):
diagnosis                  569 non-null object
radius_mean                569 non-null float64
texture_mean               569 non-null float64
perimeter_mean             569 non-null float64
area_mean                  569 non-null float64
smoothness_mean            569 non-null float64
compactness_mean           569 non-null float64
concavity_mean             569 non-null float64
concave points_mean        569 non-null float64
symmetry_mean              569 non-null float64
fractal_dimension_mean     569 non-null float64
radius_se                  569 non-null float64
texture_se                 569 non-null float64
perimeter_se               569 non-null float64
area_se                    569 non-null float64
smoothness_se              569 non-null float64
compactness_se             569 non-null float64
concavity_se               569 non-null float64
concave points_se        

In [45]:
# change de dtype pour diagnosis : object > category

df['diagnosis'] = df['diagnosis'].astype('category')

In [46]:
# Valeurs distinctes prises par diagnosis

print( df['diagnosis'].value_counts().count() )


2


In [47]:
# Ventilation des enregistrements de df suivant diagnosis

df.groupby(['diagnosis']).count()

radius_mean  texture_mean  perimeter_mean  area_mean  \
diagnosis                                                         
B                  357           357             357        357   
M                  212           212             212        212   

           smoothness_mean  compactness_mean  concavity_mean  \
diagnosis                                                      
B                      357               357             357   
M                      212               212             212   

           concave points_mean  symmetry_mean  fractal_dimension_mean  \
diagnosis                                                               
B                          357            357                     357   
M                          212            212                     212   

                    ...             radius_worst  texture_worst  \
diagnosis           ...                                           
B                   ...                      357            357   
M                   ...                      212            212   

           perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
diagnosis                                                                     
B                      357         357               357                357   
M                      212         212               212                212   

           concavity_worst  concave points_worst  symmetry_worst  \
diagnosis                                                          
B                      357                   357             357   
M                      212                   212             212   

           fractal_dimension_worst  
diagnosis                           
B                              357  
M                              212  

[2 rows x 30 columns]

In [48]:
# diagnosis : remplacement de B par 0 et M par 1

replace_map = {'diagnosis': {'B' : 0 , 'M' : 1} }

df.replace( replace_map  , inplace = True )

df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
id                                                                          
842302            1        17.99         10.38          122.80     1001.0   
842517            1        20.57         17.77          132.90     1326.0   
84300903          1        19.69         21.25          130.00     1203.0   
84348301          1        11.42         20.38           77.58      386.1   
84358402          1        20.29         14.34          135.10     1297.0   

          smoothness_mean  compactness_mean  concavity_mean  \
id                                                            
842302            0.11840           0.27760          0.3001   
842517            0.08474           0.07864          0.0869   
84300903          0.10960           0.15990          0.1974   
84348301          0.14250           0.28390          0.2414   
84358402          0.10030           0.13280          0.1980   

          concave points_mean  symmetry_mean           ...             \
id                                                     ...              
842302                0.14710         0.2419           ...              
842517                0.07017         0.1812           ...              
84300903              0.12790         0.2069           ...              
84348301              0.10520         0.2597           ...              
84358402              0.10430         0.1809           ...              

          radius_worst  texture_worst  perimeter_worst  area_worst  \
id                                                                   
842302           25.38          17.33           184.60      2019.0   
842517           24.99          23.41           158.80      1956.0   
84300903         23.57          25.53           152.50      1709.0   
84348301         14.91          26.50            98.87       567.7   
84358402         22.54          16.67           152.20      1575.0   

          smoothness_worst  compactness_worst  concavity_worst  \
id                                                               
842302              0.1622             0.6656           0.7119   
842517              0.1238             0.1866           0.2416   
84300903            0.1444             0.4245           0.4504   
84348301            0.2098             0.8663           0.6869   
84358402            0.1374             0.2050           0.4000   

          concave points_worst  symmetry_worst  fractal_dimension_worst  
id                                                                       
842302                  0.2654          0.4601                  0.11890  
842517                  0.1860          0.2750                  0.08902  
84300903                0.2430          0.3613                  0.08758  
84348301                0.2575          0.6638                  0.17300  
84358402                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [50]:
# Valeurs manquantes ?

print( df.isnull().values.sum() )

0


In [53]:
# Impute

df_val = df.values

imputer = Imputer()

imputed_df_val = imputer.fit_transform( df_val )

In [54]:
imputed_df_val


array([[ 1.     , 17.99   , 10.38   , ...,  0.2654 ,  0.4601 ,  0.1189 ],
       [ 1.     , 20.57   , 17.77   , ...,  0.186  ,  0.275  ,  0.08902],
       [ 1.     , 19.69   , 21.25   , ...,  0.243  ,  0.3613 ,  0.08758],
       ...,
       [ 1.     , 16.6    , 28.08   , ...,  0.1418 ,  0.2218 ,  0.0782 ],
       [ 1.     , 20.6    , 29.33   , ...,  0.265  ,  0.4087 ,  0.124  ],
       [ 0.     ,  7.76   , 24.54   , ...,  0.     ,  0.2871 ,  0.07039]])

In [58]:
# Normalize the ranges of the features

scaler = MinMaxScaler( feature_range = (0, 1) )

nor_imputed_df_val = scaler.fit_transform( imputed_df_val )

print( nor_imputed_df_val )

[[1.         0.52103744 0.0226581  ... 0.91202749 0.59846245 0.41886396]
 [1.         0.64314449 0.27257355 ... 0.63917526 0.23358959 0.22287813]
 [1.         0.60149557 0.3902604  ... 0.83505155 0.40370589 0.21343303]
 ...
 [1.         0.45525108 0.62123774 ... 0.48728522 0.12872068 0.1519087 ]
 [1.         0.64456434 0.66351031 ... 0.91065292 0.49714173 0.45231536]
 [0.         0.03686876 0.50152181 ... 0.         0.25744136 0.10068215]]


In [59]:
### Bagging based ensembling 

In [60]:
## Bagged Decision Trees for Classification

from sklearn import model_selection
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier

In [62]:
# Segregate the features from the labels

X = nor_imputed_df_val[:,1:9]

Y = nor_imputed_df_val[:,0]

In [69]:
kfold = model_selection.KFold( n_splits = 10 , random_state = 7 )

cart = DecisionTreeClassifier()

num_trees = 100

model = BaggingClassifier( base_estimator = cart , n_estimators = num_trees , random_state = 7 )

results = model_selection.cross_val_score( model , X , Y , cv = kfold )

print( results.mean() )


0.9385651629072681


In [ ]:
## AdaBoost Classification

In [95]:
from sklearn.ensemble import AdaBoostClassifier

seed = 7

num_trees = 100

kfold = model_selection.KFold( n_splits = 10 , random_state = seed )

model = AdaBoostClassifier( n_estimators = num_trees , random_state = seed )

results = model_selection.cross_val_score( model , X , Y , cv = kfold )

print( results.mean() )

0.9367481203007518


In [ ]:
# Voting Ensemble for Classification

In [96]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

from sklearn.ensemble import VotingClassifier

kfold = model_selection.KFold(n_splits=10, random_state=seed)

# create the sub models
estimators = []

model1 = LogisticRegression()
estimators.append( ('logistic', model1) )

model2 = DecisionTreeClassifier()
estimators.append( ('cart', model2) )

model3 = SVC()
estimators.append( ('svm', model3) )

# create the ensemble model
ensemble = VotingClassifier( estimators )

results = model_selection.cross_val_score( ensemble , X , Y , cv = kfold )

print(results.mean())

D:\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
D:\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
D:\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
D:\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `arra

0.9210213032581456


D:\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
